# Generated by Django 5.0.3 on 2024-03-14 20:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_producto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=200)),
                ('url_producto', models.JSONField()),
                ('url_imagenes', models.JSONField()),
                ('colores', models.JSONField()),
                ('estilo', models.CharField(max_length=200)),
                ('lista', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
